// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrbaGIStory.Server.Data;

#nullable disable

namespace UrbaGIStory.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260103011149_AddGeometryTables")]
    partial class AddGeometryTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UrbaGIStory.Server.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("UrbaGIStory.Server.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the user was deactivated (null if active).");

                    b.Property<Guid?>("DeactivatedBy")
                        .HasColumnType("uuid")
                        .HasComment("ID of the administrator who deactivated the user (null if active).");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasComment("Indicates whether the user is active (not deactivated). When false, the user cannot log in.");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasComment("Row version used for optimistic concurrency control. Automatically updated by the database on each update.");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("UrbaGIStory.Server.Models.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the entity.");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the entity was created (UTC).");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("ID of the user who created the entity.");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the entity was deleted (null if not deleted).");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasComment("ID of the user who deleted the entity (null if not deleted).");

                    b.Property<JsonDocument>("DynamicProperties")
                        .HasColumnType("jsonb")
                        .HasComment("Dynamic properties stored as JSONB. Properties are defined by categories assigned to the entity type.");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer")
                        .HasComment("Type of entity (building, street, plaza, etc.).");

                    b.Property<Guid?>("GeoLineId")
                        .HasColumnType("uuid")
                        .HasComment("Optional link to a line geometry. Only ONE geometry FK can be set.");

                    b.Property<Guid?>("GeoPointId")
                        .HasColumnType("uuid")
                        .HasComment("Optional link to a point geometry. Only ONE geometry FK can be set.");

                    b.Property<Guid?>("GeoPolygonId")
                        .HasColumnType("uuid")
                        .HasComment("Optional link to a polygon geometry. Only ONE geometry FK can be set.");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Whether the entity is deleted (soft delete).");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasComment("Row version used for optimistic concurrency control. Automatically updated by the database on each update.");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the entity was last updated (UTC).");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasComment("ID of the user who last updated the entity.");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Entities_CreatedBy");

                    b.HasIndex("DynamicProperties")
                        .HasDatabaseName("IX_Entities_DynamicProperties");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("DynamicProperties"), "gin");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("IX_Entities_EntityType");

                    b.HasIndex("GeoLineId")
                        .HasDatabaseName("IX_Entities_GeoLineId");

                    b.HasIndex("GeoPointId")
                        .HasDatabaseName("IX_Entities_GeoPointId");

                    b.HasIndex("GeoPolygonId")
                        .HasDatabaseName("IX_Entities_GeoPolygonId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Entities_IsDeleted");

                    b.ToTable("Entities", null, t =>
                        {
                            t.HasCheckConstraint("CK_Entities_SingleGeometry", "(\r\n                (CASE WHEN \"GeoPointId\" IS NOT NULL THEN 1 ELSE 0 END) +\r\n                (CASE WHEN \"GeoLineId\" IS NOT NULL THEN 1 ELSE 0 END) +\r\n                (CASE WHEN \"GeoPolygonId\" IS NOT NULL THEN 1 ELSE 0 END)\r\n            ) <= 1");
                        });
                });

            modelBuilder.Entity("UrbaGIStory.Server.Models.GeoLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()")
                        .HasComment("Unique identifier for the line geometry.");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()")
                        .HasComment("Date and time when the geometry was created (UTC).");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the geometry was deleted (null if not deleted).");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasComment("Optional description of the geometry.");

                    b.Property<LineString>("Geometry")
                        .HasColumnType("geometry(LineString, 4326)")
                        .HasComment("LineString geometry in WGS84 (EPSG:4326).");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Whether the geometry is deleted (soft delete).");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Name of the geometry (visible in QGIS).");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the geometry was last updated (UTC).");

                    b.HasKey("Id");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "GIST");

                    b.HasIndex("IsDeleted")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("geo_lines", (string)null);
                });

            modelBuilder.Entity("UrbaGIStory.Server.Models.GeoPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()")
                        .HasComment("Unique identifier for the point geometry.");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()")
                        .HasComment("Date and time when the geometry was created (UTC).");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the geometry was deleted (null if not deleted).");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasComment("Optional description of the geometry.");

                    b.Property<Point>("Geometry")
                        .HasColumnType("geometry(Point, 4326)")
                        .HasComment("Point geometry in WGS84 (EPSG:4326).");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Whether the geometry is deleted (soft delete).");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Name of the geometry (visible in QGIS).");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the geometry was last updated (UTC).");

                    b.HasKey("Id");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "GIST");

                    b.HasIndex("IsDeleted")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("geo_points", (string)null);
                });

            modelBuilder.Entity("UrbaGIStory.Server.Models.GeoPolygon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()")
                        .HasComment("Unique identifier for the polygon geometry.");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()")
                        .HasComment("Date and time when the geometry was created (UTC).");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the geometry was deleted (null if not deleted).");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasComment("Optional description of the geometry.");

                    b.Property<Polygon>("Geometry")
                        .HasColumnType("geometry(Polygon, 4326)")
                        .HasComment("Polygon geometry in WGS84 (EPSG:4326).");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Whether the geometry is deleted (soft delete).");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Name of the geometry (visible in QGIS).");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the geometry was last updated (UTC).");

                    b.HasKey("Id");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "GIST");

                    b.HasIndex("IsDeleted")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("geo_polygons", (string)null);
                });

            modelBuilder.Entity("UrbaGIStory.Server.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the permission.");

                    b.Property<bool>("CanRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Whether the user can read/view the entity.");

                    b.Property<bool>("CanWrite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Whether the user can write/edit the entity.");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the permission was created (UTC).");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasComment("ID of the Office Manager who created this permission.");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasComment("ID of the entity this permission applies to.");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the permission was last updated (UTC).");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasComment("ID of the Office Manager who last updated this permission.");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("ID of the user who has this permission.");

                    b.HasKey("Id");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("IX_Permissions_EntityId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Permissions_UserId");

                    b.HasIndex("UserId", "EntityId")
                        .IsUnique()
                        .HasDatabaseName("IX_Permissions_UserId_EntityId");

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("UrbaGIStory.Server.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("UrbaGIStory.Server.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("UrbaGIStory.Server.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("UrbaGIStory.Server.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbaGIStory.Server.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("UrbaGIStory.Server.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UrbaGIStory.Server.Models.Entity", b =>
                {
                    b.HasOne("UrbaGIStory.Server.Models.GeoLine", "GeoLine")
                        .WithMany("Entities")
                        .HasForeignKey("GeoLineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UrbaGIStory.Server.Models.GeoPoint", "GeoPoint")
                        .WithMany("Entities")
                        .HasForeignKey("GeoPointId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UrbaGIStory.Server.Models.GeoPolygon", "GeoPolygon")
                        .WithMany("Entities")
                        .HasForeignKey("GeoPolygonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GeoLine");

                    b.Navigation("GeoPoint");

                    b.Navigation("GeoPolygon");
                });

            modelBuilder.Entity("UrbaGIStory.Server.Models.Permission", b =>
                {
                    b.HasOne("UrbaGIStory.Server.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UrbaGIStory.Server.Models.GeoLine", b =>
                {
                    b.Navigation("Entities");
                });

            modelBuilder.Entity("UrbaGIStory.Server.Models.GeoPoint", b =>
                {
                    b.Navigation("Entities");
                });

            modelBuilder.Entity("UrbaGIStory.Server.Models.GeoPolygon", b =>
                {
                    b.Navigation("Entities");
                });
#pragma warning restore 612, 618
        }
    }
}
